### ISSUE TITLE
Installation and Quickstart

### ISSUE THREAD

**Issue by stevehorn** [TileStache/TileStache#150]
Ran through the installation and quickstart instructions in the readme. I installed mapnik via homebrew.

When I try to run `./scripts/tilestache-server.py -c tilestache.cfg` I get:

```
Steve-Macbook:TileStache stevehorn$ ./scripts/tilestache-server.py -c tilestache.cfg
Error loading Tilestache config:
Traceback (most recent call last):
  File "./scripts/tilestache-server.py", line 55, in <module>
    app = TileStache.WSGITileServer(config=options.file, autoreload=True)
  File "/Library/Python/2.7/site-packages/TileStache/__init__.py", line 340, in __init__
    self.config = parseConfigfile(config)
  File "/Library/Python/2.7/site-packages/TileStache/__init__.py", line 105, in parseConfigfile
    return Config.buildConfiguration(config_dict, dirpath)
  File "/Library/Python/2.7/site-packages/TileStache/Config.py", line 217, in buildConfiguration
    config.layers[name] = _parseConfigfileLayer(layer_dict, config, dirpath)
  File "/Library/Python/2.7/site-packages/TileStache/Config.py", line 447, in _parseConfigfileLayer
    layer.provider = _class(layer, **provider_kwargs)
  File "/Library/Python/2.7/site-packages/TileStache/Mapnik.py", line 81, in __init__
    engine = mapnik.FontEngine.instance()
NameError: global name 'mapnik' is not defined
```

Any thoughts?

**Comment by volkanunsal** [comment]
I am also getting this error in Mapnik 3 on a Mac. Any workarounds for me?

**Comment by jeromegv** [comment]
@volkanunsal Got the same error with Mapnik3 on Mac (installed from brew)

**Comment by volkanunsal** [comment]
@jeromegv Looks like there are separate [Python bindings for Mapnik now](https://github.com/mapnik/mapnik/issues/3018#issuecomment-128863228). They didn't work for me, but may work for you.

**Comment by jeromegv** [comment]
@volkanunsal Decided to save myself some trouble and get an old version of the brew formula for mapnik 2.2.0 for now.
It worked.
https://github.com/Homebrew/homebrew/blob/9724d71a2f66269b8ccbbd1b6a054782bdd30601/Library/Formula/mapnik.rb

**Comment by volkanunsal** [comment]
Wow, neat. I might do the same. Thanks for the tip!

On Mon, Aug 10, 2015 at 9:35 AM, Jérôme Gagnon-Voyer <
notifications@github.com> wrote:

> @volkanunsal <https://github.com/volkanunsal> Decided to save myself some
> trouble and get an old version of the brew formula for mapnik 2.2.0 for now.
> It worked.
>
> https://github.com/Homebrew/homebrew/blob/9724d71a2f66269b8ccbbd1b6a054782bdd30601/Library/Formula/mapnik.rb
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TileStache/TileStache/issues/150#issuecomment-129457195>
> .
>



-- 
*Volkan Unsal*
*web and mobile development*
volkanunsal.com
