### ISSUE TITLE
What version of python is required?

### ISSUE THREAD

**Issue by leblowl** [TileStache/TileStache#224]
I'm curious as I get a syntax error when importing TileStache in python 3.4.3 & I couldn't find specific info for this in the readme/docs. Is there a general way to find out this info for python modules?

**Comment by rimig** [comment]
Looks like it builds and runs tests with python 2.7:

https://github.com/TileStache/TileStache/blob/dd629731c625f8ddb44fc7093cd1a08570bf341b/.travis.yml#L7
