### ISSUE TITLE
Mapnik provider fails with Pillow==3.0.0

### ISSUE THREAD

**Issue by Xevib** [TileStache/TileStache#237]
Mapnik provider fails  when it renders an empty tile whit Pillow package in version 3.0.0

The message is:
 fromstring() has been removed. Please call frombytes() instead

The traceback is

filename: "/home/user/virtualenvs/project/local/lib/python2.7/site-packages/TileStache/__init__.py" line: 381 function: "__call__" text/code: "status_code, headers, content = requestHandler2(self.config, path_info, query_string, script_name)" 
filename: "/home/user/virtualenvs/project/local/lib/python2.7/site-packages/TileStache/__init__.py" line: 254 function: "requestHandler2" text/code: "status_code, headers, content = layer.getTileResponse(coord, extension)" 
filename: "/home/user/virtualenvs/project/local/lib/python2.7/site-packages/TileStache/Core.py" line: 425 function: "getTileResponse" text/code: "tile = self.render(coord, format)" 
filename: "/home/user/virtualenvs/project/local/lib/python2.7/site-packages/TileStache/Core.py" line: 506 function: "render" text/code: "tile = provider.renderArea(width, height, srs, xmin, ymin, xmax, ymax, coord.zoom)" 
filename: "/home/user/virtualenvs/project/local/lib/python2.7/site-packages/TileStache/Mapnik.py" line: 154 function: "renderArea" text/code: "img = Image.fromstring('RGBA', (width, height), img.tostring())" 
filename: "/home/user/virtualenvs/project/local/lib/python2.7/site-packages/PIL/Image.py" line: 2053 function: "fromstring" text/code: ""Please call frombytes() instead.")"

**Comment by jbants** [comment]
installing PIL 2.9.0 fixed this for me as a workaround.

**Comment by Xevib** [comment]
Seems the 3.0.0. breaks the API backwards becase 2.8.1 works for me but this should be solved or added on the requirements

**Comment by bjorm** [comment]
@jbants I think you meant Pillow not PIL -- just in case there are any other careless readers like me trying to find PIL 2.9.0

**Comment by jbants** [comment]
@bjorm Yup, you're correct.

**Comment by lujop** [comment]
What is the expected implementation and version that is supported?
Because if one that already has the byte versions a fix to support the Pillow 3.0 version is easy.

**Comment by alculquicondor** [comment]
addressed in #260
