### ISSUE TITLE
Tilestache slow when interrupted

### ISSUE THREAD

**Issue by trippah** [TileStache/TileStache#245]
I am using tilestache to serve mapnik OSM map, I am finding it really slow when mapnik rendering is interrupted (say when user zooms out twice with empty cache). It has to wait for the first zoom requests to all disconnect via a broken pipe error like below:

----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 37259)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------

So the user must wait for the first zoom level of tile requests to error before the next zoom level tiles can start rendering. Is there any way of speeding this up?

Also is it possible to run multiple mapnik rendering threads?

**Comment by rburhum** [comment]
What web server are you using to deploy this? NGINX + Gunicorn are usually good choices. Using the development server would cause this behavior...

**Comment by trippah** [comment]
I am using apache2 in linux.
With your setup on an empty cache, if you zoom out twice, it doesn't do broken pipe errors like mine?

**Comment by rburhum** [comment]
It does not. 

Are you using mod_wsgi then? How is it configured?

**Comment by trippah** [comment]
I am using OpenLayers3 library on an Apache2 server and rendering tiles from a postgres database through mapnik 2.3. There seems to be a request queue for the tiles that I am trying to 'flush'.

**Comment by rburhum** [comment]
There is one important part that I need to know so I can give you a good answer :)
How is Apache configured to host the python code?

- Is it through mod_wsgi? https://code.google.com/p/modwsgi/
- Is it through mod_python? http://modpython.org/
- Is it through cgi?

You may want to read this: http://stackoverflow.com/questions/3319545/mod-wsgi-mod-python-or-just-cgi

I have a feeling it is not mod_wsgi and that it is through cgi, so I am curious as to how the process pool is managed...

**Comment by trippah** [comment]
I'm using tilestache-server.py, so I'm presuming it is mod_python?

**Comment by trippah** [comment]
I just updated tilestache to the latest and it seems to be working now, but I have a problem with WebGL rendering and CORS.

"Uncaught SecurityError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The cross-origin image at http://gistimg.ornl.gov/geoserver/sandbox/wms?SERVICE=WMS&VERSION=1.3.0&REQ…846.773818498%2C3615925.2794545814%2C3442471.367389944%2C3621796.598689737 may not be loaded."

**Comment by rburhum** [comment]
and therein lies the problem :)

From tilestache-server.py (https://github.com/TileStache/TileStache/blob/master/scripts/tilestache-server.py#L6)

> It is intended for direct use only during development or for debugging TileStache.
> For the proper way to configure TileStach for serving tiles see the docs at:
> http://tilestache.org/doc/#serving-tiles

I _strongly_ recommend deploying using mod_wsgi.

**Comment by trippah** [comment]
Thanks for your assist, will look into mod_wsgi. Closing.
