### ISSUE TITLE
PIL version conflict

### ISSUE THREAD

**Issue by petulla** [TileStache/TileStache#247]
Hi

I'm not able to load the server with PIL version 1.1.7

```/anaconda/lib/python2.7/site-packages/PIL/Image.py:81: RuntimeWarning: The _imaging extension was built for another  version of Pillow or PIL```

Which version do you support? Does it work with pillow?

**Comment by petulla** [comment]
I read you support Pillow 2.9, so it is installed.

Tilestache now hangs on the command line but doesn't serve anything. I couldn't find a verbose mode. Any suggestions?

**Comment by alculquicondor** [comment]
@petulla we now support only Pillow (including 3.0+). Could you post more of your configuration file?

**Comment by aashish24** [comment]
@alculquicondor should we close this issue?
