### ISSUE TITLE
Publish release tags

### ISSUE THREAD

**Issue by sebastic** [TileStache/TileStache#265]
The CHANGELOG documents several releases after 1.49.8, the last release published on http://tilestache.org/download/

Please tag the releases in the git repository and push the tags to make the releases available via GitHub in addition to PyPI, also consider adding the missing releases to http://tilestache.org/download/.

**Comment by alculquicondor** [comment]
Hello @sebastic good suggestions. Thanks to the suggestion, we will be adding releases here on github from now on.

closes #266

**Comment by sebastic** [comment]
Can you also tag the previous releases (at least since 1.49.8)?

**Comment by alculquicondor** [comment]
I tried but github wouldn't allow me to link to old commits. I'm looking for a workaround and also trying to identify the exact commits.

**Comment by sebastic** [comment]
Pushing old tags should work (as long as they're not annotated), GitHub may disallow the fancy release markup though. That's not required for the old releases, just having the tags since the last release on tilestache.org/download for reference (and `git diff`ing) is sufficient.

**Comment by alculquicondor** [comment]
@sebastic sure, I'm on it :)
