### ISSUE TITLE
Vector MBTiles

### ISSUE THREAD

**Issue by mg262** [TileStache/TileStache#270]
It's not clear from the documentation whether TileStache supports vector MBTiles.  I'd be grateful for clarification of this.

**Comment by buma** [comment]
I also had the same question. I looked into the code and it seems it isn't supported. In [MBtiles.py](https://github.com/TileStache/TileStache/blob/master/TileStache/MBTiles.py#L78) if format of mbtiles isn't png,jpg or json exception is raised. My vector MBtiles have pbf as format. And PR #264 which added support for PBF format seems to only change files for Vector provider not MBtiles.

**Comment by buma** [comment]
I looked into the code and tried to add support for vector MBtiles since it seems it should be easy. Since only the response type is different. PBF instead of PNG/JPG/json. I get correct PBF which I can read with protocol buffer but when trying to load it with mapbox-gl I can't see anything on a map even though there are no HTTP or JS errors. Only sometimes there is python error when writing to response socket. But this can be seen in browser as error 500.

Maybe the problem is too slow response. Mapbox response times are around 360 ms. My local tilestache is 1-3 seconds.

**Comment by flyingxiang** [comment]
Hi @buma , did you merge your work on vector mbtiles back to the master branch? It should be great for you to do that.

**Comment by dhairyashil** [comment]
Hi @buma , 
we are also stuck with serving mbtiles as pbf on mapbox.
Tested with your changes and it is working fine!
So It would be really great help to community if you merge your changes to master.

**Comment by buma** [comment]
I looked into the master and it seems that this commit: https://github.com/TileStache/TileStache/commit/91b23656 added support for PBF MBtiles. It has same changes as my branches except adding GZIP header on PBF responses. Are you sure that master isn't working with PBF tiles?

**Comment by dhairyashil** [comment]
Yes, we want those GZIP header changes also. Can you please merge them also?

**Comment by sagarr** [comment]
@buma Why have you added `headers.add_header('Content-Encoding', 'gzip')` for MBTiles? because it works while serving mbtiles but doesn't work while serving vector tiles from postgis.

**Comment by tahoe** [comment]
I haven't been able to get this to work. What I have are .mbtile files with vector/pbf data. Here is the select * from metadata output, truncated...
sqlite3 2017-07-03_asia_iraq.mbtiles 'select * from metadata'                                                                                                                           
attribution|<a href="http://www.openmaptiles.org/" target="_blank">&copy; OpenMapTiles</a> <a href="http://www.openstreetmap.org/about/" target="_blank">&copy; OpenStreetMap contributors</a>                      
center|43.842805,33.22115,14                                                                                                                                                                                        
description|Extract from https://openmaptiles.org                                                                                                                                                                   
maxzoom|14                                                                                                                                                                                                          
minzoom|0                                                                                                                                                                                                           
name|OpenMapTiles                                                                                                                                                                                                   
pixel_scale|256                                                                                                                                                                                                     
mtime|1499626373833                                                                                                                                                                                                 
format|pbf                                                                                                
id|openmaptiles                                                                                           
version|3.6.1                                                                                             
maskLevel|5                                                                                                                                                                                                         
bounds|38.784,29.05167,48.90161,37.39063                                                                  
planettime|1499040000000                                                                                                                                                                                            
json|{"vector_layers":[{"maxzoom":14,"fields":{"class":"String"},"minzoom":0,"id":"water","description":""},...

Any clue how I can go from something like this to something that will be viewable in TileStache?
