### ISSUE TITLE
Tilestache.org website down

### ISSUE THREAD

**Issue by jbants** [TileStache/TileStache#300]
The [TileStache](www.tilestache.org) website is down.

**Comment by migurski** [comment]
Looks okay to me? http://www.tilestache.org/

**Comment by jbants** [comment]
Huh, maybe my internet was hiccuping. Looks good to me now.

**Comment by alculquicondor** [comment]
I saw it down 2 hours ago, then up, then down again 30 min ago. Something might not be ok in the server.

**Comment by gabefair** [comment]
Can we close this ticket?

**Comment by jbants** [comment]
I think so. I haven't seen any new issues.
