### ISSUE TITLE
Tilestache: Not able to render data from postGIS SQL

### ISSUE THREAD

**Issue by Akulkarni1** [TileStache/TileStache#301]
my tilestache.cfg is as below:
{
  "cache": {
        "name": "Disk",
        "path": "mnt/tile-cache/"
    }
    ,    
  "layers":
  {  
     "countries":
    {
      "provider": {
            "name": "vector", 
            "driver": "PostgreSQL",
            "parameters": 
             {
            "dbname": "test1",
            "host" : "localhost",
            "port" : "5432",
            "user": "postgres",
                        "password":"postgres",
                        "table": "ne_110m_admin_0_countries",
                         "query":"SELECT admin, ST_Y(ST_Centroid(wkb_geometry)) as lattitude FROM ne_110m_admin_0_countries;"

             }}}}}

I am getting error as

File "/usr/local/lib/python2.7/dist-packages/TileStache-1.51.6-py2.7.egg/TileStache/__init__.py", line 303, in requestHandler2
    print >> out, 'Known unknown!'

URL using is as below

I am using URL as localhost:8080/countries/1/1/1.json

Not able to render data.

**Comment by alculquicondor** [comment]
Can you please provide the content of the response?

**Comment by alculquicondor** [comment]
Also, can you confirm that you are running python 2.7.x?

**Comment by migurski** [comment]
What’s the `admin` column? If it’s not a PostGIS geometry, then I’m guessing you’re not selecting one and TileStache has nothing to return in vector form.

**Comment by Akulkarni1** [comment]
Hi, 
I am using python 2.7.x.
I tried with below query.
Select gid,geom AS __geometry__ from public.be-water-area_multiploygon
from the table below.
![image](https://user-images.githubusercontent.com/17604602/28954870-d1390a52-78ff-11e7-8c31-bbf506ec1f59.png)
below is the response 
![image](https://user-images.githubusercontent.com/17604602/28955150-e7da2a28-7901-11e7-95bb-a756d4e35d33.png)

![image](https://user-images.githubusercontent.com/17604602/28955161-ff21842e-7901-11e7-836e-989243b2127a.png)


Please help me with the above.

Thanks in advance.
Best regards,
Amit.

**Comment by Akulkarni1** [comment]
ok , shall try with the same.
Thanks for the help.

**Comment by Akulkarni1** [comment]
Able to render the data.
Thanks for the help.

**Comment by gabefair** [comment]
@Akulkarni1 Where did you use "io.BytesIO" to get it working?
