### ISSUE TITLE
AssertionError: applications must write bytes

### ISSUE THREAD

**Issue by jucajuca** [TileStache/TileStache#329]
Hi,

I'm getting the following error: 

python3 ./scripts/tilestache-server.py -p 7070
 * Running on http://127.0.0.1:7070/ (Press CTRL+C to quit)
127.0.0.1 - - [23/Apr/2018 11:30:18] "GET / HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 241, in write
    assert isinstance(data, bytes), 'applications must write bytes'
**AssertionError: applications must write bytes**

This is running with a reverse proxy in apache. 
Any ideas?

**Comment by jucajuca** [comment]
probably related to #279 
however with python2 I get the same error:

python ./scripts/tilestache-server.py -p 7070
 * Running on http://127.0.0.1:7070/ (Press CTRL+C to quit)
127.0.0.1 - - [23/Apr/2018 11:42:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [23/Apr/2018 11:42:18] "GET /osm/preview.html HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 241, in write
    assert isinstance(data, bytes), 'applications must write bytes'
**AssertionError: applications must write bytes**

**Comment by saadqc** [comment]
@jucajuca Any luck ?

**Comment by saadqc** [comment]
@jucajuca : Ahan. I found a solution. Hope it will help someone in future.

As the error says application must write bytes and I was returning bool. 
To resolve this, when using `yield` to return data from `iterator`. All I did was to decode data to `utf-8`. This should fix the issue.

```
    def endpoint():
          results_bulk_iter = iter([])
          response = Response(stream_with_context(bulk_update_streamed_response(results_bulk_iter)),
                            mimetype='text/plain')
        return response

    def bulk_update_streamed_response(results):
        for updated, _ in results:
            yield str(counter).decode('utf-8')

```

**Comment by akhilkumardonka** [comment]
I was using **python 2** for flask streaming and faced this issue, switching to **python 3** solved my problem.

**Comment by hamzaMahdi** [comment]
I solved it by converting the expression to string before doing yield. Here is the line of code where I did it:
yield **str**(b'--frame\r\n' b'Content-Type: image/jpeg\r\n\r\n' + bytearray(encoded_image) + b'\r\n')
