### ISSUE TITLE
TileStache offers a xyz services like tms services,not a wms server?

### ISSUE THREAD

**Issue by yh371174229** [TileStache/TileStache#351]
At start I think that it's a wms server,but when I installed it and used it ,I found it offers a xyz service like TMS .
`http://192.168.90.110:8082/building/preview.html`
I don't know if I'm right？
Any help will appreciated！！

**Comment by migurski** [comment]
You’re correct, TileStache uses ZXY tile numbering scheme similar to OpenStreetMap and others.
